export enum TODO_ACTIONS_TYPES {
  ADD_TASK = "taskList/ADD_TASK_STARTED",
  DELETE_TASK = "taskList/EDIT_TASK_STARTED",
  EDIT_TASK = "taskList/DELETE_TASK_STARTED",
  SET_TASK_STATUS = "taskList/SET_TASK_STATUS_STARTED",
}
