export enum TODO_ACTION_TYPES {
  ADD_TASK = "taskList/ADD_TASK_STARTED",
  DELETE_TASK = "taskList/DELETE_TASK_STARTED",
  UPDATE_TASK = "taskList/UPDATE_TASK_STARTED",
  SET_TASK_STATUS = "taskList/SET_TASK_STATUS_STARTED",
  GET_TASK_ARRAY = "tasklist/GET_TASK_LIST_STARTED",
}

export enum USER_ACTION_TYPES {
  GET_USER = "user/GET_USER_STARTED",
  LOGIN = "user/LOGIN_STARTED",
  SIGNUP = "user/SIGNUP_STARTED",
  LOGOUT = "user/LOGOUT",
}
